### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oehme**

### CODE REVIEW

**Comment by dhuebner** [comment]
Can one of the admins verify this patch?

**Comment by oehme** [comment]
Jenkins test

**Comment by oehme** [comment]
Jenkins test

**Comment by oehme** [comment]
Jenkins rebase

**Comment by oehme** [comment]
Jenkins rebase

**Comment by dhuebner** [comment]
Can one of the admins verify this patch?

**Comment by dhuebner** [comment]
Can one of the admins verify this patch?

**Comment by oehme** [comment]
Jenkins rebase

**Comment by oehme** [comment]
Jenkins rebase

**Comment by dhuebner** [comment]
Refer to this link for build results (access rights to CI server needed): 
extern.itemis.de/jenkins/job/xtext-pull-request-verifier/5/
Test FAILed.

**Comment by oehme** [comment]
Jenkins merge

**Comment by oehme** [comment]
Jenkins merge

**Comment by oehme** [comment]
Jenkins rebase

**Pull request closed without merging**
