### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by dhuebner**

### CODE REVIEW

**Comment by oehme** [comment]
Test this please =P

**Comment by oehme** [comment]
Test this please

**Comment by oehme** [comment]
Jenkins!!!

**Comment by oehme** [comment]
GO go go!

**Comment by oehme** [comment]
Build this

**Comment by dhuebner** [comment]
test this please

**Comment by dhuebner** [comment]
jenkins: test

**Comment by dhuebner** [comment]
Jenkins: test

**Comment by dhuebner** [comment]
Jenkins test

**Pull request merged**
